### ISSUE TITLE
ProFTPD: Cannot create Hash

### ISSUE THREAD

**Issue by TB1234** [instantlinux/docker-tools#159]
I am not able to create a Hash for the ProFTPd Image:

```python
import crypt,random,string; \
  print crypt.crypt('YOURPASSWORD', '\$6\$' + ''.join( \
[random.choice(string.ascii_letters + string.digits) \
  for _ in range(16)]))
``` 

throws an error:

```
Traceback (most recent call last):
  File "/tmp/main.py", line 2, in <module>
    import user_code
  File "/tmp/user_code.py", line 2
    print crypt.crypt('YOURPASSWORD', '\$6\$' + ''.join( \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

[Execution complete with exit code 1]
```

How can I create a password hash for an own user?

**Comment by TB1234** [comment]
OK, I can anser it myself... For python3 you need brackets...

```python
import crypt,random,string; \
  print(crypt.crypt('YOURPASSWORD', '\$6\$' + ''.join( \
[random.choice(string.ascii_letters + string.digits) \
  for _ in range(16)])))
```
